services:
  # floci is a replacement for localstack. It emulates AWS resources (sqs, sns, s3 etc) for local development
  # See: https://floci.io for more details
  floci:
    image: floci/floci:1.5.25-compat
    ports:
      - '4566:4566'
    env_file:
      - ./compose/aws.env
      - ./compose/floci.env
    volumes:
      - ./compose/floci/ready.d:/etc/floci/init/ready.d:ro

  mongodb:
    image: mongo:7.0.28
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  trade-gateway-publisher:
    build:
      args:
        DEFRA_NUGET_PAT: ${DEFRA_NUGET_PAT}
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    links:
      - 'floci:floci'
      - 'mongodb:mongodb'
    depends_on:
      floci:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      ASPNETCORE_URLS: http://+:8085
      Mongo__DatabaseUri: mongodb://mongodb:27017/
      TracesUpdateConsumer__IntraQueueUrl: http://floci:4566/000000000000/trade_gateway_publisher_intra_stream_internal_publisher.fifo
      TracesUpdateConsumer__ChedQueueUrl: http://floci:4566/000000000000/trade_gateway_publisher_ched_stream_internal_publisher.fifo
      TracesUpdatePublisher__IntraInternalTopicArn: arn:aws:sns:eu-west-2:000000000000:trade_gateway_publisher_intra_stream_internal.fifo
      TracesUpdatePublisher__IntraTopicArn: arn:aws:sns:eu-west-2:000000000000:trade_gateway_publisher_intra_updates.fifo
      TracesUpdatePublisher__ChedInternalTopicArn: arn:aws:sns:eu-west-2:000000000000:trade_gateway_publisher_ched_stream_internal.fifo
      TracesUpdatePublisher__ChedTopicArn: arn:aws:sns:eu-west-2:000000000000:trade_gateway_publisher_ched_updates.fifo
      TracesGateway__BaseUrl: http://wiremock:8089
      AWS_EMF_ENVIRONMENT: Local
      AWS_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      USE_FLOCI: true

  asb-backend:
    environment:
      SQL_WAIT_INTERVAL: 0
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "secretPassword!"
      ACCEPT_EULA: "Y"
    depends_on:
      sqledge:
        condition: service_healthy
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    ports:
      - "5672:5672"
      - "5300:5300"
    pull_policy: always
    volumes:
      - "./compose/asb.json:/ServiceBus_Emulator/ConfigFiles/Config.json"

  asb:
    image: alpine/curl:latest
    depends_on:
      asb-backend:
        condition: service_started
    command: ["tail", "-f", "/dev/null"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://asb-backend:5300/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  sqledge:
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 5s
      test: timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/1433'
      timeout: 5s
    image: mcr.microsoft.com/azure-sql-edge:latest
    #    On some platforms there are compatibility issues with running Azure SQL Edge e.g. M1 Macs with later Docker versions.
    #    If SQL Edge does not work for you, try swapping out with SQL Server image instead
    #    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "secretPassword!"
      
  wiremock:
    image: "holomekc/wiremock-gui:latest"
    ports:
      # This is just an example of a port mapping
      - "8088:8089"
      - "8084:8088"
    command:
      "--port 8089 --https-port 8088 --max-request-journal 1000 --local-response-templating"
    volumes:
      - ./root-dir:/home/wiremock:ro
    environment:
      WIREMOCK_MY_VAR: "systemValue response templating feature"

################################################################################

volumes:
  mongodb-data:
